import { Project } from './app/models/project.model';
import { Task } from './app/models/task.model';

export const PROJECTS_MOCK: Project[] = [
  {
    id: 'p-001',
    name: 'Customer Analytics Platform',
    status: 'active',
    startDate: '2025-01-10',
    endDate: '2025-06-30',
    ownerId: 'u-101',
    progress: 45,
  },
  {
    id: 'p-002',
    name: 'Internal DevOps Dashboard',
    status: 'paused',
    startDate: '2024-11-01',
    endDate: '2025-04-15',
    ownerId: 'u-102',
    progress: 30,
  },
  {
    id: 'p-003',
    name: 'Mobile App Redesign',
    status: 'active',
    startDate: '2025-02-01',
    endDate: '2025-05-20',
    ownerId: 'u-103',
    progress: 60,
  },
  {
    id: 'p-004',
    name: 'Payment Gateway Migration',
    status: 'completed',
    startDate: '2024-08-10',
    endDate: '2024-12-01',
    ownerId: 'u-104',
    progress: 100,
  },
  {
    id: 'p-005',
    name: 'Search Performance Optimization',
    status: 'active',
    startDate: '2025-01-25',
    endDate: '2025-04-10',
    ownerId: 'u-105',
    progress: 52,
  },
  {
    id: 'p-006',
    name: 'User Permissions Refactor',
    status: 'paused',
    startDate: '2024-12-15',
    endDate: '2025-03-30',
    ownerId: 'u-101',
    progress: 20,
  },
  {
    id: 'p-007',
    name: 'Marketing Automation Tool',
    status: 'active',
    startDate: '2025-02-12',
    endDate: '2025-07-01',
    ownerId: 'u-106',
    progress: 35,
  },
  {
    id: 'p-008',
    name: 'Real-Time Notification Service',
    status: 'active',
    startDate: '2025-01-05',
    endDate: '2025-04-25',
    ownerId: 'u-102',
    progress: 68,
  },
  {
    id: 'p-009',
    name: 'Legacy System Decommissioning',
    status: 'completed',
    startDate: '2024-05-01',
    endDate: '2024-11-15',
    ownerId: 'u-107',
    progress: 100,
  },
  {
    id: 'p-010',
    name: 'Role-Based Access Control (RBAC)',
    status: 'active',
    startDate: '2025-02-20',
    endDate: '2025-06-10',
    ownerId: 'u-104',
    progress: 40,
  },
  {
    id: 'p-011',
    name: 'API Gateway Standardization',
    status: 'paused',
    startDate: '2024-10-05',
    endDate: '2025-02-28',
    ownerId: 'u-108',
    progress: 55,
  },
  {
    id: 'p-012',
    name: 'Data Export & Reporting Module',
    status: 'active',
    startDate: '2025-01-18',
    endDate: '2025-05-05',
    ownerId: 'u-105',
    progress: 48,
  },
  {
    id: 'p-013',
    name: 'Infrastructure Cost Optimization',
    status: 'active',
    startDate: '2025-02-03',
    endDate: '2025-08-01',
    ownerId: 'u-106',
    progress: 25,
  },
  {
    id: 'p-014',
    name: 'Audit Logging & Compliance',
    status: 'completed',
    startDate: '2024-09-01',
    endDate: '2024-12-20',
    ownerId: 'u-103',
    progress: 100,
  },
  {
    id: 'p-015',
    name: 'Multi-Tenant Architecture Upgrade',
    status: 'active',
    startDate: '2025-01-30',
    endDate: '2025-09-15',
    ownerId: 'u-101',
    progress: 18,
  },
];

export const TASKS_MOCK: Task[] = [
  {
    id: 't-001',
    projectId: 'p-001',
    name: 'Design analytics dashboard layout',
    component: 'UI',
    dueDate: '2025-02-10',
    status: 'completed',
  },
  {
    id: 't-002',
    projectId: 'p-001',
    name: 'Implement metrics aggregation service',
    component: 'Backend',
    dueDate: '2025-02-18',
    status: 'in progress',
  },
  {
    id: 't-003',
    projectId: 'p-001',
    name: 'Create chart components',
    component: 'Frontend',
    dueDate: '2025-02-20',
    status: 'verify',
  },
  {
    id: 't-004',
    projectId: 'p-002',
    name: 'Audit CI/CD pipeline configuration',
    component: 'DevOps',
    dueDate: '2025-01-30',
    status: 'completed',
  },
  {
    id: 't-005',
    projectId: 'p-002',
    name: 'Add environment-specific secrets',
    component: 'DevOps',
    dueDate: '2025-02-05',
    status: 'verify',
  },
  {
    id: 't-006',
    projectId: 'p-002',
    name: 'Refactor deployment scripts',
    component: 'DevOps',
    dueDate: '2025-02-12',
    status: 'in progress',
  },
  {
    id: 't-007',
    projectId: 'p-003',
    name: 'User research synthesis',
    component: 'UX',
    dueDate: '2025-01-25',
    status: 'completed',
  },
  {
    id: 't-008',
    projectId: 'p-003',
    name: 'Create high-fidelity mobile mockups',
    component: 'UI',
    dueDate: '2025-02-08',
    status: 'verify',
  },
  {
    id: 't-009',
    projectId: 'p-003',
    name: 'Implement responsive layout',
    component: 'Frontend',
    dueDate: '2025-02-15',
    status: 'in progress',
  },
  {
    id: 't-010',
    projectId: 'p-004',
    name: 'Migrate legacy payment flows',
    component: 'Backend',
    dueDate: '2024-11-20',
    status: 'completed',
  },
  {
    id: 't-011',
    projectId: 'p-004',
    name: 'Validate payment reconciliation',
    component: 'Finance',
    dueDate: '2024-11-28',
    status: 'completed',
  },
  {
    id: 't-012',
    projectId: 'p-005',
    name: 'Profile search latency',
    component: 'Performance',
    dueDate: '2025-02-02',
    status: 'completed',
  },
  {
    id: 't-013',
    projectId: 'p-005',
    name: 'Optimize database indexes',
    component: 'Database',
    dueDate: '2025-02-09',
    status: 'in progress',
  },
  {
    id: 't-014',
    projectId: 'p-005',
    name: 'Add performance monitoring alerts',
    component: 'Monitoring',
    dueDate: '2025-02-14',
    status: 'verify',
  },
  {
    id: 't-015',
    projectId: 'p-006',
    name: 'Review role permission matrix',
    component: 'Security',
    dueDate: '2025-02-05',
    status: 'backlog',
  },
  {
    id: 't-016',
    projectId: 'p-006',
    name: 'Refactor authorization middleware',
    component: 'Backend',
    dueDate: '2025-02-18',
    status: 'backlog',
  },
  {
    id: 't-017',
    projectId: 'p-007',
    name: 'Define automation workflow rules',
    component: 'Product',
    dueDate: '2025-02-07',
    status: 'completed',
  },
  {
    id: 't-018',
    projectId: 'p-007',
    name: 'Implement campaign triggers',
    component: 'Backend',
    dueDate: '2025-02-16',
    status: 'in progress',
  },
  {
    id: 't-019',
    projectId: 'p-007',
    name: 'QA automation scenarios',
    component: 'QA',
    dueDate: '2025-02-22',
    status: 'verify',
  },
  {
    id: 't-020',
    projectId: 'p-008',
    name: 'Design notification payload schema',
    component: 'Architecture',
    dueDate: '2025-01-28',
    status: 'completed',
  },
  {
    id: 't-021',
    projectId: 'p-008',
    name: 'Implement WebSocket listener',
    component: 'Backend',
    dueDate: '2025-02-06',
    status: 'in progress',
  },
  {
    id: 't-022',
    projectId: 'p-008',
    name: 'Add delivery retry logic',
    component: 'Backend',
    dueDate: '2025-02-12',
    status: 'verify',
  },
  {
    id: 't-023',
    projectId: 'p-010',
    name: 'Define RBAC permission scopes',
    component: 'Security',
    dueDate: '2025-02-04',
    status: 'completed',
  },
  {
    id: 't-024',
    projectId: 'p-010',
    name: 'Implement role assignment UI',
    component: 'Frontend',
    dueDate: '2025-02-15',
    status: 'in progress',
  },
  {
    id: 't-025',
    projectId: 'p-010',
    name: 'Access control regression testing',
    component: 'QA',
    dueDate: '2025-02-20',
    status: 'verify',
  },
];
